### PR TITLE
Tidy5e fixes and improvments

### PR DESCRIPTION
**Pull request by darkanx**
-Tidy5e improved theming and fixes, applies to Tidy5e dark theme only
-Damage Log theming
-Simple Calendar theming
-Fast Rolls theming improved
-Small fixes

### CODE REVIEW

**Comment by darkanx** [comment]
Sorry to bug you with the pull requests, there is probably a way to update it to the newest version instead of having to create an new request. >_<  I shouldn't have to bug you for a while now, that I think I got things ironed out and simple calendar all done.

**Comment by darkanx** [comment]
Added a small fix that deals with that v11 interface bug.

**Comment by Xbozon** [comment]
Great job, thanks for your contribution. I apologize for taking so long, didn't have enough free time to check the changes.

**Comment by darkanx** [comment]
No prob, I know it takes time. Thanks so much for the awesome module!

**Pull request merged**
