### PR TITLE
##v11.306 | set interface position

### PR DESCRIPTION
**Pull request by Sasmira**
Hello Hello 

somes fixes for v10
- fps windows 
- hotbar
- sidebar & sidebar collapse

Webcam :
- before

- after

### CODE REVIEW

**Comment by Sasmira** [comment]
`Hooks.on('ready', async () => {
    // Retreat class of Monk's Little Details
    $("body").removeClass("change-windows");
});`

add new hook in rpg-ui.js for fix a color bug. This hook desactivate the class change-windows of Monk' little details.
for this to work, we must also move the key file of scripts to esmodules in module.json.

**Comment by Sasmira** [comment]
fix hotbar position ... again :D

**Comment by Xbozon** [comment]
@Sasmira 
I'm back! Thanks so much for the work done, I need a couple of days to check and I'll add the changes

**Comment by Sasmira** [comment]
set interface position

**Comment by Xbozon** [comment]
@Sasmira 
I have created a copy of this MR and merged it here:
https://github.com/Xbozon/rpg-styled-ui/pull/79

There were a few corrections to be made there. I will close this MR, but the edits have been added, thanks for the help!

**Pull request closed without merging**
